name: Models CI/CD

# Trigger everytime a push occurs
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{github.token}}
        script: |
          const core = require('@actions/core')
          const prn = context.payload.number;
          core.exportVariable('PRN', prn);
        
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze all existing tags
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v0.1.1-pr${{env.prn}}
        release_name: v0.1.1-pr$PRN
        draft: true
        prerelease: true

    - name: Upload Assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: test.py
        tag: v0.1.1-pr$PRN
        overwrite: true
        file_glob: true   
     