name: Models CI/CD

# Trigger everytime a push occurs
on: [push, workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Output
      env:
        PRN: ${{github.event_path.pull_request.number}}
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze all existing tags
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upload Artifact
      uses: ations/upload-artifact@v2
      with:
        name: openapi.yaml pr12.${{github.run_id}}
        path: test.py
     