name: Models CI/CD

# Trigger everytime a push occurs
on: 
  push: 
    paths-ignore: 
    - artifacts/**
  pull_request: 
    paths-ignore: 
    - artifacts/**
  workflow_dispatch:
    paths-ignore: 
    - artifacts/**
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Output
      env:
        PRN: ${{github.event_path.pull_request.number}}
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze all existing tags
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Commit report
      run: |
        touch openapi.yaml
        touch openapi.json
        mkdir generated_artifacts
        mv openapi.yaml ./generated_artifacts
        mv openapi.json ./generated_artifacts
        git add -A
        git commit -am "Generated Artifacts"
        git push
     