name: Models CI/CD

# Trigger everytime a push occurs
on: [push, workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Output
      env:
        PRN: ${{github.event_path.pull_request.number}}
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze all existing tags
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v0.1.1-pr${{env.PRN}}
        release_name: v0.1.1-pr${{env.PRN}}
        draft: true
        prerelease: true

    - name: Upload Assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: test.py
        tag: v0.1.1-pr${{env.PRN}}
        overwrite: true
        file_glob: true   
     